title: Pick Up Strength » Strength is contagious. Spread the power.
description: Pick Up Strength is a community.
baseurl: "" # the subpath of your site, e.g. /blog
url: "pickupstrength.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    Pick Up Strength
author-image:   1.jpg
author-job:     Strength » Nutrition » Lifestyle
author-email:   hello@pickupstrength.com # Add your email for contant form.
author-twitter:  pickupstrength # Add your twitter account
author-instagram: pickupstrength
about-author:  H E L L O - Welcome to Pick Up Strength. I am tm, the creator of Pick Up Strength and currently reside in the United States. Thanks for stopping by and feel free to reach out to me if you have any questions on P.U.S. ❤ tm

# Social settings
social-twitter:   
social-facebook:  Pick-Up-Strength-240188306610507
social-github:    
social-pinterest: pickupstrength
social-instagram: pickupstrength
social-youtube: pickupstrength
social-vk:   
social-linkedin:

# Newsletter
mailchimp: https://pickupstrength.us19.list-manage.com/subscribe/post?u=60ebcb361753fd00c76787553&amp;id=d48bb0efd3 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: UA-123488355-1 # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: #mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 2 #7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor


