title: Pick Up Strength » Strength is contagious. Spread the power.
description: Strength is contagious. A healthy dose of encouragement and confidence.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://pickupstrength.com" # the base hostname & protocol for your site, e.g. http://example.com
date: 2018-08-01 20:13:18 +0200
modified: now

# Author
author-name:    Pick Up Strength
author-image:   pickupstrength.jpg
author-job:     Strength » Nutrition » Lifestyle
author-mantra-1: Strength is contagious. 
author-mantra-2: Be a humble hummingbird.
author-email:   pickupstrength@gmail.com #hello@pickupstrength.com # Add your email for contant form.
author-twitter:  pickupstrength # Add your twitter account
author-instagram: pickupstrength
author-youtube : pickupstrength
about-author: Welcome to Pick Up Strength. I’m a weightlifter, yogi, lifestyle, and nutrition lover sharing knowledge and inspiration on incorporating P.U.S. philosophy in your life. Thanks for stopping by and following along.  ❤ tm 

# Social settings
social-twitter:   pickupstrength
social-facebook:  Pick-Up-Strength-240188306610507
social-github:    
social-pinterest: #pickupstrength
social-instagram: pickupstrength
social-youtube: channel/UCLeyIA2hNpC8rx7u_j7ecVQ?sub_confirmation=1 #pickupstrength
social-vk:   #https://plus.google.com/u/1/100590609275665997066
social-linkedin:

# Newsletter
mailchimp: https://pickupstrength.us19.list-manage.com/subscribe/post?u=60ebcb361753fd00c76787553&amp;id=d48bb0efd3 # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: UA-123488355-1 # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: https-pickupstrength-com #mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:categories/:title/
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-seo-tag

paginate: 4 #7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass  
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
  - node_modules
  - package.json


